// Polygon.idl: источник языка IDL для Polygon
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(7a091d01-6d0e-484b-a73c-fc4df15144be),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IPolyCtl : IDispatch
{
	[propput, bindable, requestedit, id(DISPID_BORDERCOLOR)]
	HRESULT BorderColor([in]OLE_COLOR clr);
	[propget, bindable, requestedit, id(DISPID_BORDERCOLOR)]
	HRESULT BorderColor([out, retval]OLE_COLOR* pclr);
	[propput, bindable, requestedit, id(DISPID_FILLCOLOR)]
	HRESULT FillColor([in]OLE_COLOR clr);
	[propget, bindable, requestedit, id(DISPID_FILLCOLOR)]
	HRESULT FillColor([out, retval]OLE_COLOR* pclr);

	[propget, id(1), helpstring("Ко-во сторон")] HRESULT Sides([out, retval] SHORT* pVal);
	[propput, id(1), helpstring("Ко-во сторон")] HRESULT Sides([in] SHORT newVal);

	[propget, id(2), helpstring("Цвет графика")] HRESULT GraphColor([out, retval] OLE_COLOR* pVal);
	[propput, id(2), helpstring("Цвет графика")] HRESULT GraphColor([in] OLE_COLOR newVal);
	[propget, id(3), helpstring("Цвет фона")] HRESULT BackgroundColor([out, retval] OLE_COLOR* pVal);
	[propput, id(3), helpstring("Цвет фона")] HRESULT BackgroundColor([in] OLE_COLOR newVal);

	[propget, id(4), helpstring("Минимум X")] HRESULT XMin([out, retval] DOUBLE* pVal);
	[propput, id(4), helpstring("Минимум X")] HRESULT XMin([in] DOUBLE newVal);
	[propget, id(5), helpstring("Максимум X")] HRESULT XMax([out, retval] DOUBLE* pVal);
	[propput, id(5), helpstring("Максимум X")] HRESULT XMax([in] DOUBLE newVal);
	[propget, id(6), helpstring("Минимум Y")] HRESULT YMin([out, retval] DOUBLE* pVal);
	[propput, id(6), helpstring("Минимум Y")] HRESULT YMin([in] DOUBLE newVal);
	[propget, id(7), helpstring("Максимум Y")] HRESULT YMax([out, retval] DOUBLE* pVal);
	[propput, id(7), helpstring("Максимум Y")] HRESULT YMax([in] DOUBLE newVal);
};

[
	uuid(81f97e0e-c4e2-4ce7-b42a-3fe8e6084bcf),
	version(1.0),
]
library PolygonLib
{
	importlib("stdole2.tlb");
	[
		uuid(46c3617e-b7bd-4f87-87c3-6d4cf57aaf1a)
	]
	dispinterface _IPolyCtlEvents
	{
		properties:
		methods:
			[id(1), helpstring("Левая кнопка мыши - показать график")] void LButton([in] LONG x, [in] LONG y);
			[id(2), helpstring("Правая кнопка мыши - скрыть график")] void RButton([in] LONG x, [in] LONG y);
	};
	[
		uuid(2205e542-da76-4e54-89d9-9564966cca4b),
		control
	]
	coclass PolyCtl
	{
		[default] interface IPolyCtl;
		[default, source] dispinterface _IPolyCtlEvents;
	};
};

